import { Qna } from '../../../types';

export default {
  id: 'random',
  keywords: [
    'cheese',
    'chicken',
    'fud',
    'lambo',
    'spicoli',
    'tooth man',
    'lmao',
    'mike',
  ],
  enabled: false,
  reactions: ['🍗', '🧀'],
  allowUserTag: false,
  answers: [
    'I have created the perfect thing: Blackpepper and Slap FUD dish',
    'Cheese goes well with other cheeses',
    'You can never be sure about chickens taking over the world',
    'Where did I put my Spicoli Brown Pants?',
    'The Lambo does not steer far from the cheese',
    'I can curl 200 pounds of Gouda cheese',
    'Whenever you catch a FUDster, give him some blackpepper',
    'Exhaling is like eating cheese underwater',
    'Here comes the coffee grounds maniac who will eat all the cheese and call out all the FUDsters!',
    "It's time to kick ass and chew bubble gum. And I'm all out of gum...",
    'Would you send a block of cheese into space?',
    'I have carefully crafted the most atrocious coffee grounds, blackpepper, and molten cheese face masks for the FUDsters!',
    'The chickens here are so chonky I can barely identify them from garden gnomes',
    "You've been gnomed!",
    "Don't let the cheese bugs bite!",
    'If I spin fast enough - I can smell myself',
    'Phase 2 is all about having tons of cheese and tokens',
    "Let's eat some creamy cheesey cheese chicken",
  ],
} as Qna;
