import { Qna } from '../../../types';

export default {
  id: 'roadmap',
  keywords: [
    'when roadmap',
    'when is the roadmap',
    'updates on roadmap',
    'news about roadmap',
    'news about the roadmap',
  ],
  enabled: true,
  reactions: [],
  allowUserTag: true,
  answers: `
  **Here's the preliminary Swych Roadmap!**
  *Some things are still being finalized and are yet to receive concrete dates*
  * **Perpetual Exchange and Phase 2 Launch**
  Direct integration with the token and NFTs is needed. The team needs to make sure the revenue is generated sustainably and equitably.
  Phase 2 will have no limits on sales or buys. Users can be rewarded with tokens for participating on the platform and trading, along with real yield generation.

  * **Lottery V3**
  The once great lottery system is receiving a facelift and some juicy upgrades!
  The percentage of fees generated by the Perpetual Dex will go into creating the world's biggest DeFi lottery. 
  What's so great about it?
  Users will be able to earn real yield. From the lottery!
  Just by buying tickets you will have access to a huge prize and real yield rewards.

  * **NFT Integration**
  The NFT will be a substantial part in this ecosystem allowing users access and a wide range of tools. 
  Level them up and get exciting benefits! 
  It's a new utility where you will be able to get these new NFTs, compete have a leaderboard system, and much more!

  * **Platform Expansion**
  The team is playing with the idea of adding more utility and elements to the ecosystem. 
  Have an idea? 
  Feel free to post your suggestions!

  **The team is collectiong feedback and adjusting release timeframes and other things. So expect to hear more feedback and communication if anything changes!**
  `,
} as Qna;
